server:
  port: 8080
  servlet:
    context-path: /collection
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  application:
    name: my-mapper-test
mybatis:
  type-aliases-package:  com.yangzai.collection.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-cfg.xml